### ISSUE TITLE
Admin Dashboard - users

### ISSUE THREAD

**Issue by duyng404** [duyng404/cafapp-returns#12]
An interface to browse and search for users in Admin Dashboard

**Comment by duyng404** [comment]
Task 1: Get a GUI client for mysql. I recommend Emma (http://www.linuxandubuntu.com/home/emma-a-lightweight-database-management-tool-for-linux). But if u find others u can use it. My support for these will be limited because I have never used these things.

After installing, running, and connecting to the local cafapp database:

- try to view the users table. you should see 1 user which is yourself.
- try running cafapp, place some orders, then go back to the db, look at the orders table, you should see the order you just placed.
- now, use Emma to add two new users. Make up random names for them. Also random email, gus username, etc.

**Comment by duyng404** [comment]
Task 2: Make a function in `gorm/user.go`, named `GetAllUser()`. The function has no parameters and will return a list of user (`[]User`) and an error. It should simply select all the users in the database.

Look at a similar function in `gorm/destination.go` as an example

**Comment by duyng404** [comment]
Task 3: Make a new gin endpoint.

- The endpoint should be in the group `apiadmin` and should be at `/view-users`.
- The handler function should be named `handleAdminViewUsers()`, and be put in the file `gin/adminHandlers.go`
- the function takes in a pointer to gin.Context (like all other handler functions)
- the function should call the function you just made in the last step, to retrieve a list of all users.
- when calling that function it should handle errors properly
- the function will return http status OK and JSON object of the list of users it just get.

**Comment by duyng404** [comment]
Task 4: Clone & Run cafapp-admin

- simply clone, `npm i`, then `npm start`
- run it at the same time with the backend.
- play around with the queue. go place a new order, then move it to prep, to shipping, etc.

**Comment by duyng404** [comment]
Task 5 (admin):

- Create a new container for the "users" page.
- For this task let's only have the `render()` function first. Just write up the html skeleton with fake data, so that you can focus on making it look decent first, before plugging real data into it. ("decent" because u don't have to do it too cẩn thận).
- The page should look similar to the user dash (go to /dash to see). Minus the "Account Details" part. Make a similar table. It should have the columns Full Name, Gus Username, and Total Orders.

**Comment by lamngue** [comment]
Task 2: 

> func (u *User) GetAllUser() ([]User, error) {
	var users []User
	err := DB.Raw(`
		SELECT u.*
		FROM users u
		WHERE u.deleted_at IS NULL
	`).Scan(&users).Error
	return users, err
}

Em ko thấy function populate users array, why does this work?

**Comment by duyng404** [comment]
@lamngue Not sure what you are asking, but the function you just wrote should work to get all users. Line 3 from that snippet you posted is the line that does the job. Here is the summary of what it does

- `.Raw()` will run a raw SQL query: `SELECT u.* FROM users u WHERE u.deleted_at IS NULL`: select everything from users table (including all columns like full names, gus id etc).
- `.Scan()` will put the result *into* the variable users. We give it an array because there will be multiple results. Gorm will figure it out automatically and put the correct data in the correct place.
- `.Error` will return the error (if any) when we ran the query. Errors could be: database is not reachable, does not have select permission, or error could be that `.Scan()` received an object that does not match the data selected.
- Note that if the query cannot find anything (as in, the table is empty for example), there would be no errors returned. The `users` array would simply be empty.

**Comment by lamngue** [comment]
Task 3: On routes.go file, added new api group: 

> apiadmin := router.Group("/apiadmin")
	{
		apiadmin.GET("/view-users", handleAdminViewUsers)
	}

on handleAdminViewUsers.go file, added a new function that gets all the users:

> func handleAdminViewUsers(c *gin.Context) {
	//make users array to hold the retrieved users
	var users gorm.User
	allUsers, err := users.GetAllUser()
	if err != nil {
		logger.Error("There's an error retrieving users: ", err)
		return
	}
	c.JSON(200, gin.H{
		"users": allUsers,
	})
}

**Comment by lamngue** [comment]
Task 4, I tried placing an order and saw corresponding changes in the "orders" table (status code). Is this the only change I can see?

**Comment by lamngue** [comment]
Task 5: Created new react page for users

**Comment by duyng404** [comment]
Task 6: I just updated the users page layout a little bit, you should take a look. I added a "search filter" section, as well as the "user details" section.

Now what you should do is, make it so that when this page loads, it will make a GET request to `/apiadmin/view-users`. It will then take the response and display it into the table. Each row should correspond with one user.

If for some reason the response is empty (no users found), the table would be hidden, and a "No result" text would be displayed instead (I have this commented out right below the table).

Task 7: Make a new endpoint in the `apiadmin` group. Should be a GET request to `/view-users/:userid`. This endpoint will return info for one specific user (the `User` object) AND all the orders made by that user (a list of `Order` object). There's a function `GetAllOrderFromUser` in `gorm/order.go` that is available to use for this. Also read [this part of gin docs](https://github.com/gin-gonic/gin#parameters-in-path) for how to get the `:userid` from the path.

Task 8: Now you should make the "View Details" button work. When the button is clicked, the corresponding user's detail should be displayed in the "User Details" section. To do this, make a request to `/view-users/12` (replace 12 with the correct user id). Then it should read the response and display it onto the "User Details" section.

What should it display? User Fullname, Gus Username, Gus ID, and then a table of orders, just like in user dashboard.

**Comment by lamngue** [comment]
Done with task 6, here's the screen shot
![abc](https://user-images.githubusercontent.com/34784901/52760664-f51ffd80-3042-11e9-90cf-f81e2267d48d.png)

**Comment by lamngue** [comment]
Done task 7 and 8. The code might not be efficient. 
![screenshot from 2019-02-16 10-13-49](https://user-images.githubusercontent.com/34784901/52893862-96d65480-31d3-11e9-8b49-e91085280b5f.png)

**Comment by duyng404** [comment]
Task 9: Let's make the Search Filter box actually works now.

- Make it so that when the "Search" button is clicked, the frontend send a request to backend, but this time with extra query params. Should still use the endpoint `/view-users`, but add params accordingly, for example:
  - When the page first load, the GET request would simply be `/view-users`
  - If searching by full name, the GET request would be `/view-users?fullname=abc`
  - If searching by gus username, the GET request would be `/view-users?gususername=abc`
  - If searching by both fullname & username, it would be `/view-users?fullname=abc&gususername=abc`
- Also do the same thing for sort. Something like `/view-users?sort=something`
- You can decide what those query params would be named. `?sort=id-desc` or `?order=id-reverse` or whatever makes sense.
- Layout nitpick:
  - Notice how "Search filter" and "Search results" are not bold. Make "User details" and "Order details" not bold as well, please.
  - The user details part, don't need to text-center it. If you want to make it center, use the layout similar to "Account Details" in user dashboard.
  - Rename "Order Details" to "Past orders by <username>"
- Code nitpick:
  - Make sure the browser console has no warnings (currently it has a warning about "keys" prop. Please fix it)
  - Also the terminal console as well. Currently it is complaining about importing "api" but unused.

**Comment by duyng404** [comment]
Task 10: Make this page URL-friendly, what this means:

- Admins should be able to go to the url, `admin.gustiecaf.app/users?fullname=john&gususername=abc&sort=name-reverse` and it will automatically set the search to "John" for fullname, "abc" for gususername, and sort by name, in reverse. Basically, the URL should set the search filters automatically.
- When pressing the "Search" button, the URL changes as well. For example if you put "John" in the fullname box and click "Search", the URL changes to `admin.gustiecaf.app/?fullname=John`.

Maybe this will help: https://tylermcginnis.com/react-router-query-strings/

**Comment by lamngue** [comment]
Done task 9, hopefully it has no bug.

![sadd](https://user-images.githubusercontent.com/34784901/53305162-89def280-38b0-11e9-8ab7-04547d5c3b7a.png)

**Comment by lamngue** [comment]
Done with task 10, admin users can type url and the user dashboard will automatically filter results. 

Also when they click "search", the url with corresponding queries will appear on the url bar.
